// flow-typed signature: 750b2d64f194658ee7d5900e8c71c6dd
// flow-typed version: <<STUB>>/gonzales-pe_v^4.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gonzales-pe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gonzales-pe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gonzales-pe/bin/gonzales' {
  declare module.exports: any;
}

declare module 'gonzales-pe/lib/gonzales' {
  declare module.exports: any;
}

declare module 'gonzales-pe/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gonzales-pe/bin/gonzales.js' {
  declare module.exports: $Exports<'gonzales-pe/bin/gonzales'>;
}
declare module 'gonzales-pe/lib/gonzales.js' {
  declare module.exports: $Exports<'gonzales-pe/lib/gonzales'>;
}
declare module 'gonzales-pe/webpack.config.js' {
  declare module.exports: $Exports<'gonzales-pe/webpack.config'>;
}
