name: yarn-build
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
